django/note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
]

django/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

django/notes/models.py
from django.db import models

class Topic(models.Model):
  text = models.CharField(max_length=200)
  date_added = models.DateTimeField(auto_now_add=True)

  def __str__(self):
    return self.text

class Entry(models.Model):
  topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
  text = models.TextField()
  date_added = models.DateTimeField(auto_now_add=True)

  class Meta:
    verbose_name_plural = 'entries'

  def __str__(self):
    return f'{self.text[:25]}...'

django/notes/views.py
from django.shortcuts import render
from .models import Topic

def index(request):
  """Home page for Note"""
  return render(request, 'notes/index.html')

def topics(request):
  """Show all topics"""
  topics = Topic.objects.order_by('date_added')
  context = {'topics':topics}
  return render(request, 'notes/topics.html', context)

def topic(request, topic_id):
  """Show one topic and all articles for it"""
  topic = Topic.objects.get(id=topic_id)
  entries = topic.entry_set.order_by('-date_added')
  context = {'topic':topic, 'entries':entries}
  return render(request, 'notes/topic.html', context)

django/notes/templates/notes/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ノート</title>
</head>
<body>
  <h1><a href="{% url 'notes:index' %}">ノート</a>・
  <a href="{% url 'notes:topics' %}">トピック一覧</a></h1>

  {% block content %}{% endblock content %}
</body>
</html>

django/notes/templates/notes/index.html
{% extends "notes/base.html" %}
{% block content %}
<p>ノートに各トピックについて備忘録など、気づいたことを記録できます。</p>
{% endblock content %}

django/notes/templates/notes/topic.html
{% extends "notes/base.html" %}

{% block content %}

<p>トピック： {{ topic }}</p>
<p>記事：</p>
<ul>
  {% for entry in entries %}
  <li>
    <p>{{ entry.date_added|date:'Y年m月d日 H:i' }}</p>
    <p>{{ entry.text|linebreaks }}</p>
  </li>
  {% empty %}
    <li>このトピックにはまだ記事がありません。</li>
  {% endfor %}
</ul>

{% endblock content %}

django/notes/templates/notes/topics.html
{% extends "notes/base.html" %}

{% block content %}

<p>トピック一覧</p>

<ul>
  {% for topic in topics %}
    <li>
      <a href="{% url 'notes:topic' topic.id %}">{{ topic }}</a>
    </li>
  {% empty %}
    <li>トピックはまだ作成されていません。</li>
  {% endfor %}
</ul>

{% endblock content %}